Repository Team-Goraebab/Goraebab-Backend, pull requests merged in 2024-10, with the labels that each got.

#33 [Docs/#31] Improve Swagger API documentation
  src/main/java/api/goraebab/domain/blueprint/controller/BlueprintController.java
  src/main/java/api/goraebab/domain/blueprint/dto/BlueprintReqDto.java
  src/main/java/api/goraebab/domain/blueprint/dto/BlueprintsResDto.java
  src/main/java/api/goraebab/domain/remote/database/controller/StorageController.java
  src/main/java/api/goraebab/domain/remote/database/dto/StorageReqDto.java
  src/main/java/api/goraebab/domain/remote/database/dto/StorageResDto.java
  src/main/java/api/goraebab/domain/remote/docker/controller/DaemonController.java
  src/main/java/api/goraebab/domain/remote/docker/dto/DaemonReqDto.java
  src/main/java/api/goraebab/domain/remote/docker/dto/DaemonResDto.java
  src/main/java/api/goraebab/global/exception/ErrorCode.java
Labels: documentation

#34 [Refactor/#17] Remove Harbor
  src/main/java/api/goraebab/domain/remote/harbor/controller/HarborController.java
  src/main/java/api/goraebab/domain/remote/harbor/dto/HarborDetailResDto.java
  src/main/java/api/goraebab/domain/remote/harbor/dto/HarborReqDto.java
  src/main/java/api/goraebab/domain/remote/harbor/dto/HarborResDto.java
  src/main/java/api/goraebab/domain/remote/harbor/entity/Harbor.java
  src/main/java/api/goraebab/domain/remote/harbor/mapper/HarborMapper.java
  src/main/java/api/goraebab/domain/remote/harbor/repository/HarborRepository.java
  src/main/java/api/goraebab/domain/remote/harbor/service/HarborService.java
  src/main/java/api/goraebab/domain/remote/harbor/service/HarborServiceImpl.java
Labels: new feature

#35 [Feature/#25] Parse blueprint and implement Docker execution based on parsed data
  build.gradle
  src/main/java/api/goraebab/domain/blueprint/controller/BlueprintController.java
  src/main/java/api/goraebab/domain/blueprint/dto/BlueprintReqDto.java
  src/main/java/api/goraebab/domain/blueprint/dto/BridgeInfoDto.java
  src/main/java/api/goraebab/domain/blueprint/dto/ContainerInfoDto.java
  src/main/java/api/goraebab/domain/blueprint/dto/HostInfoDto.java
  src/main/java/api/goraebab/domain/blueprint/dto/ParsedDataDto.java
  src/main/java/api/goraebab/domain/blueprint/entity/Blueprint.java
  src/main/java/api/goraebab/domain/blueprint/repository/BlueprintRepository.java
  src/main/java/api/goraebab/domain/blueprint/service/BlueprintService.java
  src/main/java/api/goraebab/domain/blueprint/service/BlueprintServiceImpl.java
  src/main/java/api/goraebab/domain/blueprint/service/DockerSyncService.java
  src/main/java/api/goraebab/domain/blueprint/service/DockerSyncServiceImpl.java
  src/main/java/api/goraebab/domain/blueprint/service/HtmlParserService.java
  src/main/java/api/goraebab/domain/blueprint/service/HtmlParserServiceImpl.java
  src/main/java/api/goraebab/global/exception/CustomException.java
  src/main/java/api/goraebab/global/exception/ErrorCode.java
  src/main/java/api/goraebab/global/util/DockerClientUtil.java
Labels: enhancement

#40 [Feature/#38] Handle all errors using ErrorCode
  src/main/java/api/goraebab/domain/blueprint/controller/BlueprintController.java
  src/main/java/api/goraebab/domain/blueprint/service/BlueprintService.java
  src/main/java/api/goraebab/domain/blueprint/service/BlueprintServiceImpl.java
  src/main/java/api/goraebab/domain/blueprint/service/DockerSyncServiceImpl.java
  src/main/java/api/goraebab/domain/remote/database/service/StorageServiceImpl.java
  src/main/java/api/goraebab/domain/remote/docker/service/DaemonServiceImpl.java
  src/main/java/api/goraebab/global/exception/ErrorCode.java
Labels: enhancement

#44 [Bugfix/#43] Replace RestTemplate with RestClient
  Dockerfile
  build.gradle
  docker-compose.yml
  src/main/java/api/goraebab/domain/config/AppConfig.java
  src/main/java/api/goraebab/global/util/ConnectionUtil.java
Labels: bug

#46 [Feature/#45] Improve Docker Sync service
  docker-compose.yml
  src/main/java/api/goraebab/domain/blueprint/controller/BlueprintController.java
  src/main/java/api/goraebab/domain/blueprint/dockerObject/CustomConfig.java
  src/main/java/api/goraebab/domain/blueprint/dockerObject/CustomContainer.java
  src/main/java/api/goraebab/domain/blueprint/dockerObject/CustomHost.java
  src/main/java/api/goraebab/domain/blueprint/dockerObject/CustomImage.java
  src/main/java/api/goraebab/domain/blueprint/dockerObject/CustomIpam.java
  src/main/java/api/goraebab/domain/blueprint/dockerObject/CustomMount.java
  src/main/java/api/goraebab/domain/blueprint/dockerObject/CustomNetwork.java
  src/main/java/api/goraebab/domain/blueprint/dockerObject/CustomNetworkSettings.java
  src/main/java/api/goraebab/domain/blueprint/dockerObject/CustomPort.java
  src/main/java/api/goraebab/domain/blueprint/dockerObject/CustomVolume.java
  src/main/java/api/goraebab/domain/blueprint/dockerObject/ProcessedData.java
  src/main/java/api/goraebab/domain/blueprint/dto/BlueprintReqDto.java
  src/main/java/api/goraebab/domain/blueprint/dto/BridgeInfoDto.java
  src/main/java/api/goraebab/domain/blueprint/dto/ContainerInfoDto.java
  src/main/java/api/goraebab/domain/blueprint/dto/HostInfoDto.java
  src/main/java/api/goraebab/domain/blueprint/dto/ParsedDataDto.java
  src/main/java/api/goraebab/domain/blueprint/entity/Blueprint.java
  src/main/java/api/goraebab/domain/blueprint/service/BlueprintServiceImpl.java
  src/main/java/api/goraebab/domain/blueprint/service/DockerSyncService.java
  src/main/java/api/goraebab/domain/blueprint/service/DockerSyncServiceImpl.java
  src/main/java/api/goraebab/domain/blueprint/service/HtmlParserService.java
  src/main/java/api/goraebab/domain/blueprint/service/HtmlParserServiceImpl.java
  src/main/java/api/goraebab/global/util/DockerClientUtil.java
Labels: new feature

#50 [Bugfix/#49] Rollback blueprint isRemote
  src/main/java/api/goraebab/domain/blueprint/entity/Blueprint.java
  src/main/java/api/goraebab/domain/blueprint/service/BlueprintServiceImpl.java
  src/main/java/api/goraebab/domain/remote/database/service/StorageServiceImpl.java
Labels: bug

#51 [Refactor/#48] Add github actions which checks gradle build
  .github/workflows/gradle-build-without-test.yml
Labels: refactor

#52 [Bugfix/#42] Change Linux image
  Dockerfile
Labels: bug

#56 [Feature/#55] Modify CustomMount/Volume and Improve Blueprint Data Processing
  src/main/java/api/goraebab/domain/blueprint/dockerObject/CustomMount.java
  src/main/java/api/goraebab/domain/blueprint/dto/BlueprintReqDto.java
  src/main/java/api/goraebab/domain/blueprint/entity/Blueprint.java
  src/main/java/api/goraebab/domain/blueprint/service/BlueprintServiceImpl.java
  src/main/java/api/goraebab/domain/blueprint/service/DockerSyncServiceImpl.java
  src/main/java/api/goraebab/global/exception/ErrorCode.java
Labels: enhancement

#41 [Feature/#37] Support for Multiple DBMS Types
  build.gradle
  db/mariadb/init.sql
  db/oracle/init.sql
  db/postgresql/init.sql
  docker-compose.mariadb.yml
  docker-compose.mysql.yml
  docker-compose.oracle.yml
  docker-compose.postgresql.yml
  src/main/java/api/goraebab/config/AppConfig.java
  src/main/java/api/goraebab/config/CorsConfig.java
  src/main/java/api/goraebab/config/JpaConfig.java
  src/main/java/api/goraebab/config/SwaggerConfig.java
  src/main/java/api/goraebab/domain/blueprint/service/DockerSyncServiceImpl.java
  src/main/java/api/goraebab/domain/remote/database/dto/StorageReqDto.java
  src/main/java/api/goraebab/domain/remote/database/dto/StorageResDto.java
  src/main/java/api/goraebab/domain/remote/database/entity/DBMS.java
  src/main/java/api/goraebab/domain/remote/database/service/StorageServiceImpl.java
  src/main/java/api/goraebab/global/entity/BaseEntity.java
  src/main/java/api/goraebab/global/util/ConnectionUtil.java
  src/main/resources/application.yml
  start.bat
  start.sh
Labels: new feature
